import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import Providers from "@/store/Providers";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "GZR-PAVILION",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Providers>
      <AuthProvider>
        
        {children}
        <Toaster />
        </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
